using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using RepoReadiness.Configuration;
using RepoReadiness.Models;

namespace RepoReadiness.Services;

public static class ReportGenerator
{
    public static void GenerateReport(string repoName)
    {
        var sb = new StringBuilder();
        int totalScore = AssessmentConfig.Scores.Values.Sum();
        int maxScore = CalculateMaxScore();
        string grade = CalculateGrade(totalScore, maxScore);

        sb.AppendLine($"# Repository Readiness Report: {repoName}");
        sb.AppendLine();
        sb.AppendLine($"**Assessment Date:** {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"**Tool Version:** 2.0");
        sb.AppendLine($"**Copilot CLI:** {(AssessmentConfig.CopilotAvailable ? "Available" : "Not available")}");
        sb.AppendLine();
        sb.AppendLine($"## Overall Score: {totalScore}/{maxScore} ({grade})");
        sb.AppendLine();
        sb.AppendLine(GetGradeDescription(grade));
        sb.AppendLine();

        sb.AppendLine("## Category Breakdown");
        sb.AppendLine();
        sb.AppendLine("| Category | Score | Max |");
        sb.AppendLine("|----------|-------|-----|");

        var maxScores = GetMaxScores();
        foreach (var kvp in AssessmentConfig.Scores)
        {
            sb.AppendLine($"| {kvp.Key} | {kvp.Value} | {maxScores[kvp.Key]} |");
        }
        sb.AppendLine();

        sb.AppendLine("## Detailed Findings");

        foreach (var kvp in AssessmentConfig.Findings)
        {
            AddCategorySection(sb, kvp.Key, kvp.Value);
        }

        sb.AppendLine();
        sb.AppendLine("## Priority Actions");
        sb.AppendLine();

        var allRecommendations = AssessmentConfig.Findings
            .SelectMany(f => f.Value.Recommendations.Select(r => (Category: f.Key, Recommendation: r)))
            .Take(5)
            .ToList();

        if (allRecommendations.Any())
        {
            int i = 1;
            foreach (var rec in allRecommendations)
            {
                sb.AppendLine($"{i}. **[{rec.Category}]** {rec.Recommendation}");
                i++;
            }
        }
        else
        {
            sb.AppendLine("No critical recommendations - repository is well-configured!");
        }

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*Generated by Repository Readiness Assessment Tool v2.0*");

        // Save report to the tool's directory, not the assessed repo
        var toolDir = AppDomain.CurrentDomain.BaseDirectory;
        // Navigate up from bin/Debug/net10.0 to the project root
        var projectRoot = Path.GetFullPath(Path.Combine(toolDir, "..", "..", ".."));
        var reportsDir = Path.Combine(projectRoot, "readiness-reports");
        Directory.CreateDirectory(reportsDir);
        var reportPath = Path.Combine(reportsDir, $"{repoName}-readiness-report_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.md");
        File.WriteAllText(reportPath, sb.ToString());

        Console.WriteLine($"\nReport saved to: {reportPath}");
    }

    private static void AddCategorySection(StringBuilder sb, string category, CategoryFindings findings)
    {
        sb.AppendLine();
        sb.AppendLine($"### {category}");

        if (findings.Strengths.Any())
        {
            sb.AppendLine();
            sb.AppendLine("**Strengths:**");
            foreach (var s in findings.Strengths)
                sb.AppendLine($"- {s}");
        }

        if (findings.Weaknesses.Any())
        {
            sb.AppendLine();
            sb.AppendLine("**Weaknesses:**");
            foreach (var w in findings.Weaknesses)
                sb.AppendLine($"- {w}");
        }

        if (findings.Recommendations.Any())
        {
            sb.AppendLine();
            sb.AppendLine("**Recommendations:**");
            foreach (var r in findings.Recommendations)
                sb.AppendLine($"- {r}");
        }

        if (!findings.Strengths.Any() && !findings.Weaknesses.Any() && !findings.Recommendations.Any())
        {
            sb.AppendLine();
            sb.AppendLine("*No specific findings for this category.*");
        }
    }

    private static Dictionary<string, int> GetMaxScores()
    {
        return new Dictionary<string, int>
        {
            { "Build", 25 },
            { "Run", 20 },
            { "Test", 20 },
            { "CodeUnderstanding", 20 },
            { "Documentation", 15 },
            { "CustomInstructions", 15 },
            { "CustomAgents", 10 },
            { "AgentSkills", 10 }
        };
    }

    private static int CalculateMaxScore()
    {
        return GetMaxScores().Values.Sum(); // 135 base + potential Copilot bonuses
    }

    private static string CalculateGrade(int score, int maxScore)
    {
        double percentage = (double)score / maxScore;
        return percentage switch
        {
            >= 0.9 => "A",
            >= 0.8 => "B",
            >= 0.7 => "C",
            >= 0.6 => "D",
            _ => "F"
        };
    }

    private static string GetGradeDescription(string grade)
    {
        return grade switch
        {
            "A" => "> Excellent! This repository is highly optimized for GitHub Copilot assistance.",
            "B" => "> Good! This repository is well-prepared for Copilot with minor improvements possible.",
            "C" => "> Adequate. Some improvements needed to maximize Copilot effectiveness.",
            "D" => "> Needs Work. Several areas require attention for effective Copilot usage.",
            _ => "> Significant improvements needed before this repository can effectively use Copilot."
        };
    }

    public static void DisplaySummary()
    {
        Console.WriteLine();
        Console.WriteLine("═══════════════════════════════════════");
        Console.WriteLine("           ASSESSMENT SUMMARY          ");
        Console.WriteLine("═══════════════════════════════════════");
        Console.WriteLine();

        var maxScores = GetMaxScores();
        foreach (var kvp in AssessmentConfig.Scores)
        {
            var bar = new string('█', kvp.Value * 20 / maxScores[kvp.Key]);
            var empty = new string('░', 20 - bar.Length);
            Console.WriteLine($"{kvp.Key,-20} [{bar}{empty}] {kvp.Value,3}/{maxScores[kvp.Key]}");
        }

        Console.WriteLine();
        int total = AssessmentConfig.Scores.Values.Sum();
        int max = CalculateMaxScore();
        Console.WriteLine($"Total Score: {total}/{max} ({CalculateGrade(total, max)})");
        Console.WriteLine();
    }
}